# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5d96726f9b76f09723f89963059b61666b60dc3a7f1be0cd21ea0ef23265642d933cfa1208e2d71e867d07fb2215047db37ab2e078df62f06664f76ba4823cbc

test:
  secret_key_base: 4043c4808a252a1b8afa955c479d75d96c843ba4ff061bb4d2f3885b0804da4199c55703a58a36919a2fa364e3f7bb686e578a2cfbb43ac4b82fa58a56a072a0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
